name: 🚀 Deploy Landing to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clona el repo
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ Instala Node.js y cachea dependencias
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      # 3️⃣ Instala dependencias
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Compila el proyecto
      - name: Build
        run: npm run build

      # 5️⃣ Despliega a GitHub Pages (rama gh-pages)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
